### ISSUE TITLE
weird format of course description

### ISSUE THREAD

**Issue by chelseaY119** [rizgif/2800-202310-BBY09#26]
<img width="330" alt="Screenshot 2023-05-24 at 00 41 56" src="https://github.com/rizgif/2800-202310-BBY09/assets/122335568/59fe5148-2d6a-44cb-8d65-7a2ef3fb9189">

courseId=64656ce5452dc0470936d368

**Comment by heesun-task** [comment]
<img width="1512" alt="image" src="https://github.com/rizgif/2800-202310-BBY09/assets/65277541/35c89c0b-d818-4cf7-8f0a-cac68ce3b925">

I checked the data, and I think the original data comes strange.
It's because some dataset does not includes line-break for their data.

But I replaced 4spaces as 1 line-break before, so I removed it.

<img width="530" alt="image" src="https://github.com/rizgif/2800-202310-BBY09/assets/65277541/057ef85e-3746-423f-8db8-352b342a9820">
so this is the final result.

**Comment by heesun-task** [comment]
@chelseaY119 I pushed the change on dev, so you can check!

**Comment by chelseaY119** [comment]
good!
